[package]
name = "svd2ral"
version = "0.0.1"
authors = ["Vadim Kaushan <admin@disasm.info>"]
keywords = ["stm32", "embedded", "no_std"]
categories = ["embedded", "no-std"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
svd-parser = "0.9.0"
anyhow = "1.0.33"
